### PR TITLE
System apps -> App prop viewer

### PR DESCRIPTION
**Pull request by wadkarsatish**
## Proposed changes

Update angular version to v18
Fixes the issue of loading app prop viewer. 

## Issue
A breaking change in angular 18 about control flow
For more details please find below link

https://angularindepth.com/posts/1525/diving-into-the-new-angular-control-flow-internals

### CODE REVIEW

**Review by DivergentEuropeans — COMMENTED** [review]
```
lastrakou@RS-PF3N3W6D MINGW64 ~/zlux/satish-zlux-app-manager/system-apps/app-prop-viewer/webClient (system-apps-app-prop-viewwer)
$ npm i && npm run build
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: org.zowe.zlux.appmanager.app.propview.webclient@2.0.0
npm error Found: @angular-devkit/build-angular@12.0.5
npm error node_modules/@angular-devkit/build-angular
npm error   dev @angular-devkit/build-angular@"~18.0.0" from the root project
npm error
npm error Could not resolve dependency:
npm error dev @angular-devkit/build-angular@"~18.0.0" from the root project
npm error
npm error Conflicting peer dependency: typescript@5.4.5
npm error node_modules/typescript
npm error   peer typescript@">=5.4 <5.5" from @angular-devkit/build-angular@18.0.7
npm error   node_modules/@angular-devkit/build-angular
npm error     dev @angular-devkit/build-angular@"~18.0.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error C:\Users\lastrakou\AppData\Local\npm-cache\_logs\2024-08-13T17_22_08_674Z-eresolve-report.txt

```

**Comment by wadkarsatish** [comment]
@DivergentEuropeans I have removed the angular cli and angular build related packages and tested with npm. Its working now for me. Please verify.

**Comment by DivergentEuropeans** [comment]
Thanks @wadkarsatish that fixed that error. But during run-time, opening App Prop Viewer, I get a non-loaded app with console error

```
main.js:7 ERROR Error: Script error for "@angular/common", needed by: /ZLUX/plugins/org.zowe.zlux.appmanager.app.propview/web/main.js
https://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:168:17)
    at HTMLScriptElement.onScriptError (require.js:1738:36)
    at o.invokeTask (main.js:60:195564)
    at Object.onInvokeTask (main.js:7:69168)
    at o.invokeTask (main.js:60:195485)
    at R.runTask (main.js:60:190787)
    at s.invokeTask [as invoke] (main.js:60:196649)
    at f (main.js:60:203772)
    at p (main.js:60:204068)
    at HTMLScriptElement.h (main.js:60:204335)
handleError @ main.js:7
next @ main.js:7
next @ main.js:3
_next @ main.js:3
next @ main.js:3
(anonymous) @ main.js:3
Qc @ main.js:3
next @ main.js:3
emit @ main.js:7
(anonymous) @ main.js:7
invoke @ main.js:60
run @ main.js:60
ru

[...]

(anonymous) @ main.js:35
invoke @ main.js:60
onInvoke @ main.js:7
invoke @ main.js:60
run @ main.js:60
(anonymous) @ main.js:61
invokeTask @ main.js:60
onInvokeTask @ main.js:7
invokeTask @ main.js:60
runTask @ main.js:60
g @ main.js:60
invokeTask @ main.js:60
f @ main.js:60
p @ main.js:60
h @ main.js:60Understand this error
main.js:7 ERROR Error: Script error for "@angular/core", needed by: /ZLUX/plugins/org.zowe.zlux.appmanager.app.propview/web/main.js
https://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:168:17)
    at HTMLScriptElement.onScriptError (require.js:1738:36)
    at o.invokeTask (main.js:60:195564)
    at Object.onInvokeTask (main.js:7:69168)
    at o.invokeTask (main.js:60:195485)
    at R.runTask (main.js:60:190787)
    at s.invokeTask [as invoke] (main.js:60:196649)
    at f (main.js:60:203772)
    at p (main.js:60:204068)
    at HTMLScriptElement.h (main.js:60:204335)
```
    
    I am using 'angular-version-update-code-refactoring' for Desktop

**Comment by DivergentEuropeans** [comment]
v2.x/staging doesn't build, hence 'angular-version-update-code-refactoring' used

**Comment by DivergentEuropeans** [comment]
```
ERROR in ./src/app/window-manager/mvd-window-manager/window/window.component.css
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve 'assets/images/window/expand-inactive.png' in 'C:\Users\lastrakou\zlux\satish-zlux-app-manager\virtual-desktop\src\app\window-manager\mvd-window-manager\window'
    at finishWithoutResolve (C:\Users\lastrakou\zlux\satish-zlux-app-manager\virtual-desktop\node_modules\enhanced-resolve\lib\Resolver.js:564:18)
    at C:\Users\lastrakou\zlux\satish-zlux-app-manager\virtual-desktop\node_modules\enhanced-resolve\lib\Resolver.js:656:15
    at C:\Users\lastrakou\zlux\satish-zlux-app-manager\virtual-desktop\node_modules\enhanced-resolve\lib\Resolver.js:718:5
    at eval (eval at create (C:\Users\lastrakou\zlux\satish-zlux-app-manager\virtual-desktop\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at C:\Users\lastrakou\zlux\satish-zlux-app-manager\virtual-desktop\node_modules\enhanced-resolve\lib\Resolver.js:718:5
    at eval (eval at create (C:\Users\lastrakou\zlux\satish-zlux-app-manager\virtual-desktop\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at C:\Users\lastrakou\zlux\satish-zlux-app-manager\virtual-desktop\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:89:43
    at C:\Users\lastrakou\zlux\satish-zlux-app-manager\virtual-desktop\node_modules\enhanced-resolve\lib\Resolver.js:718:5
    at eval (eval at create (C:\Users\lastrakou\zlux\satish-zlux-app-manager\virtual-desktop\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at C:\Users\lastrakou\zlux\satish-zlux-app-manager\virtual-desktop\node_modules\enhanced-resolve\lib\Resolver.js:718:5
 @ ./src/app/window-manager/mvd-window-manager/window/window.component.ts 204:21-54
 @ ./src/app/window-manager/mvd-window-manager/window-manager.module.ts 28:25-61
 @ ./src/desktop.ts 27:30-100

```

**Pull request merged**
